# Generated by Django 4.0.4 on 2022-05-29 06:33

import django.utils.datetime_safe
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AvatarName', models.CharField(max_length=100)),
                ('AvatarSchool', models.CharField(default='WHU', max_length=100)),
                ('AvatarMajor', models.CharField(default='信息管理与信息系统', max_length=100)),
                ('AvatarProfile', models.TextField(null=True)),
                ('AvatarAddress', models.TextField(null=True)),
                ('AvatarPhone', models.CharField(max_length=100, null=True)),
                ('AvatarMail', models.TextField(null=True)),
                ('AvatarComment', models.TextField(null=True)),
                ('AvatarImg', models.ImageField(null=True, upload_to='plogs/static')),
            ],
        ),
        migrations.CreateModel(
            name='plog',
            fields=[
                ('plog_id',
                 models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('plog_title', models.CharField(max_length=100)),
                ('plog_content', models.TextField()),
                ('plog_datetime', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('plog_abstract', models.TextField(null=True)),
                ('plog_img1', models.ImageField(null=True, upload_to='media')),
                ('plog_img2', models.ImageField(null=True, upload_to='media')),
                ('plog_img3', models.ImageField(null=True, upload_to='media')),
                ('plog_img4', models.ImageField(null=True, upload_to='media')),
                ('plog_img5', models.ImageField(null=True, upload_to='media')),
                ('plog_img6', models.ImageField(null=True, upload_to='media')),
                ('plog_img7', models.ImageField(null=True, upload_to='media')),
                ('plog_img8', models.ImageField(null=True, upload_to='media')),
                ('plog_img9', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
