# Generated by Django 4.0.4 on 2022-05-29 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('plogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='id',
            new_name='AvatarId',
        ),
    ]
