# Generated by Django 4.0.4 on 2022-05-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('plogs', '0002_rename_id_avatar_avatarid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='AvatarImg',
        ),
        migrations.AddField(
            model_name='avatar',
            name='AvatarPhoto',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
